version: '3.8'

services:
  # .NET Backend Service
  backend:
    build:
      context: .
      dockerfile: dot-net-quiz/backend/Dockerfile
    ports:
      - "5023:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PORT=8080
    networks:
      - app-network

  # Next.js Frontend Service
  frontend:
    build:
      context: .
      dockerfile: dot-net-quiz/frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_BASE=http://backend:8080
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge