version: '3.8'

services:
  # .NET Backend Service
  backend:
    build:
      context: ./dot-net-quiz/backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - PORT=8080
    networks:
      - app-network

  # Next.js Frontend Service
  frontend:
    build:
      context: ./dot-net-quiz/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE=http://backend:8080
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge