FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY dot-net-quiz/backend/backend.csproj ./dot-net-quiz/backend/
RUN dotnet restore ./dot-net-quiz/backend/backend.csproj
COPY dot-net-quiz/backend/. ./dot-net-quiz/backend/
WORKDIR /src/dot-net-quiz/backend
RUN dotnet publish backend.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 80
ENTRYPOINT ["dotnet", "backend.dll"]