services:
  - type: web
    name: fullstack-academy-backend
    # Change from docker to dotnet runtime to avoid Docker registry issues
    runtime: dotnet
    plan: free
    rootDir: dot-net-quiz/backend
    buildCommand: dotnet publish -c Release
    startCommand: dotnet backend.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: PORT
        value: 8080
    healthCheckPath: /api/health
    autoDeploy: true

  - type: web
    name: fullstack-academy-frontend
    # Change from docker to node runtime to avoid Docker registry issues
    runtime: node
    plan: free
    rootDir: dot-net-quiz/frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_BASE
        value: https://fullstack-academy-backend.onrender.com
    healthCheckPath: /
    autoDeploy: true