name: Content Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-content:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: './package.json'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run content validation
      run: node scripts/content-validation-framework.js
    
    - name: Run link checker
      run: node scripts/link-checker.js
    
    - name: Run final validation
      run: node scripts/final-validation.js
    
    - name: Run route validator
      run: node scripts/route-validator.js